public class Consts {
    public static final String QUEUE = 'Queue';
    public static final String REGIONAL_DISPATCH_QUEUE = 'Regional_Dispatch';

    public static final String HIGH_PRIORITY = 'High';
    public static final String MEDIUM_PRIORITY = 'Medium';

    public static final String FEED_ITEM = FeedItem.getSObjectType().getDescribe().getName();

    public static final String BEAR_ALERT = 'BearAlert';
}
